nelmio_cors:
    # defaults:
    #     origin_regex: true
    #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    #     allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    #     allow_headers: ['Content-Type', 'Authorization']
    #     expose_headers: ['Link']
    #     max_age: 3600
    # paths:
    #     '^/': null
    # defaults:
    #     origin_regex: true
    #     allow_credentials: true
    #    # Access-Control-Allow-Origin: true
    #     allow_origin: ['*']
    #     allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    #     allow_headers: ['Content-Type', 'Authorization']
    #     expose_headers: ['Link']
    #     max_age: 42300
    # paths:
    #     '^/': null
  
    # defaults:
    #     allow_credentials: true
    #     allow_origin: ['*']
    #     allow_headers: []
    #     allow_methods: []
    #     expose_headers: []
    #     max_age: 42300
    #     hosts: []
    #     origin_regex: false
    #     forced_allow_origin_value: ~
    #     skip_same_as_origin: true
    # paths:
    #     '^/api/':
    #         allow_origin: ['*']
    #         allow_headers: ['X-Custom-Auth']
    #         allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
    #         max_age: 3600
    #     '^/':
    #         origin_regex: true
    #         allow_origin: ['*']
    #         allow_headers: ['X-Custom-Auth']
    #         allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
    #         max_age: 3600
    #         hosts: ['^api\.']
    defaults:
        allow_origin: ['*']  # Adjust with your frontend URL
        allow_methods: ['POST', 'OPTIONS']  # Add the HTTP methods you need
        allow_headers: ['Content-Type', 'Authorization']  # Add the headers you need
        max_age: 3600  # Cache preflight requests for one hour

    paths:
        '^/api/': # Adjust the path to match your API endpoints
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600