nelmio_cors:
   
    defaults:
        allow_origin: ['*']  # Adjust with your frontend URL
        allow_methods: ['POST', 'OPTIONS']  # Add the HTTP methods you need
        allow_headers: ['Content-Type', 'Authorization']  # Add the headers you need
        max_age: 3600  # Cache preflight requests for one hour

    paths:
        '^/api/': # Adjust the path to match your API endpoints
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600