twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/assets/images': images
        '%kernel.project_dir%/public/assets/styles': styles
    strict_variables: true    
when@test:
    twig:
        strict_variables: true
